name: FakeMessages
main: bl4ckscor3.plugin.fmsg.core.FakeMessages
version: 1.2.2
author: bl4ckscor3
description: Displays fake join/leave messages and more!
commands:
    fjoin:
        description: Displays a leave message.
        usage: /<command> [name]
        aliases: [fj,fakejoin]
        permission: fmsg.use
    fleave:
        description: Displays a fake leave message.
        usage: /<command> [name]
        aliases: [fl,fakeleave]
        permission: fmsg.use

permissions:
    fmsg.use:
        description: Allows access to all FakeMessages commands.
        default: op