name: FakeMessages
main: bl4ckscor3.plugin.fmsg.core.FakeMessages
version: 1.3.1.1
author: bl4ckscor3
description: Displays fake join/leave messages and more!
commands:
    fjoin:
        description: Displays a leave message.
        usage: /<command> [name]
        aliases: [fj,fakejoin]
        permission: fmsg.use
    fleave:
        description: Displays a fake leave message.
        usage: /<command> [name]
        aliases: [fl,fakeleave]
        permission: fmsg.use
    fcheck:
        description: Checks if a player has fakeleft. Only works on players which are online.
        usage: /<command> <name>
        aliases: [fc,fakecheck]
        permission: fmsg.check

permissions:
    fmsg.use:
        description: Allows access to fakeleave and fakejoin.
        default: op
    fmsg.check:
        description: Allows access to check if a player has fakeleft.
        default: op