name: FakeMessages
main: bl4ckscor3.plugin.fmsg.core.FakeMessages
version: 1.4.3
author: bl4ckscor3
description: Displays fake join/leave messages and more!
commands:
    fjoin:
        description: Displays a join message and unvanishes the user if online.
        usage: /<command> [name]
        aliases: [fj,fakejoin]
    fleave:
        description: Displays a fake leave message and vanishes the user of online.
        usage: /<command> [name]
        aliases: [fl,fakeleave]
    fcheck:
        description: Checks if a player has fake-left.
        usage: /<command <name>
        aliases: [fr]

permissions:
    fmsg.*:
        description: Gives access to all FakeMessages commands.
        children:
            fmsg.use: true
            fmsg.check: true
            fmsg.reload: true
    fmsg.use:
        description: Allows access to fakeleave and fakejoin.
        default: op
    fmsg.check:
        description: Allows access to check if a player has fake-left.
        default: op
    fmsg.reload:
        description: allows access to reload the configuration file.
        default: op
